/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./app/__root"
import { Route as BaseImport } from "./app/_base"
import { Route as BaseBlogPostIdIndexImport } from "./app/_base/blog_/$postId/index"
import { Route as BaseBlogPostIdRouteImport } from "./app/_base/blog_/$postId/route"
import { Route as BaseBlogIndexImport } from "./app/_base/blog/index"
import { Route as BaseBlogRouteImport } from "./app/_base/blog/route"
import { Route as BaseIndexImport } from "./app/_base/index"
import { Route as BaseSurveysSurveyIdIndexImport } from "./app/_base/surveys_/$surveyId/indexx"
import { Route as BaseSurveysSurveyIdRouteImport } from "./app/_base/surveys_/$surveyId/routee"
import { Route as BaseSurveysIndexImport } from "./app/_base/surveys/index"
import { Route as BaseSurveysRouteImport } from "./app/_base/surveys/route"

// Create/Update Routes

const BaseRoute = BaseImport.update({
  id: "/_base",
  getParentRoute: () => rootRoute,
} as any)

const BaseIndexRoute = BaseIndexImport.update({
  path: "/",
  getParentRoute: () => BaseRoute,
} as any)

const BaseSurveysRouteRoute = BaseSurveysRouteImport.update({
  path: "/surveys",
  getParentRoute: () => BaseRoute,
} as any)

const BaseBlogRouteRoute = BaseBlogRouteImport.update({
  path: "/blog",
  getParentRoute: () => BaseRoute,
} as any)

const BaseSurveysIndexRoute = BaseSurveysIndexImport.update({
  path: "/",
  getParentRoute: () => BaseSurveysRouteRoute,
} as any)

const BaseBlogIndexRoute = BaseBlogIndexImport.update({
  path: "/",
  getParentRoute: () => BaseBlogRouteRoute,
} as any)

const BaseSurveysSurveyIdRouteRoute = BaseSurveysSurveyIdRouteImport.update({
  path: "/surveys/$surveyId",
  getParentRoute: () => BaseRoute,
} as any)

const BaseBlogPostIdRouteRoute = BaseBlogPostIdRouteImport.update({
  path: "/$postId",
  getParentRoute: () => BaseBlogRouteRoute,
} as any)

const BaseSurveysSurveyIdIndexRoute = BaseSurveysSurveyIdIndexImport.update({
  path: "/",
  getParentRoute: () => BaseSurveysSurveyIdRouteRoute,
} as any)

const BaseBlogPostIdIndexRoute = BaseBlogPostIdIndexImport.update({
  path: "/",
  getParentRoute: () => BaseBlogPostIdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_base": {
      id: "/_base"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof BaseImport
      parentRoute: typeof rootRoute
    }
    "/_base/blog": {
      id: "/_base/blog"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BaseBlogRouteImport
      parentRoute: typeof BaseImport
    }
    "/_base/surveys": {
      id: "/_base/surveys"
      path: "/surveys"
      fullPath: "/surveys"
      preLoaderRoute: typeof BaseSurveysRouteImport
      parentRoute: typeof BaseImport
    }
    "/_base/": {
      id: "/_base/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof BaseIndexImport
      parentRoute: typeof BaseImport
    }
    "/_base/blog/$postId": {
      id: "/_base/blog/$postId"
      path: "/$postId"
      fullPath: "/blog/$postId"
      preLoaderRoute: typeof BaseBlogPostIdRouteImport
      parentRoute: typeof BaseBlogRouteImport
    }
    "/_base/surveys/$surveyId": {
      id: "/_base/surveys/$surveyId"
      path: "/surveys/$surveyId"
      fullPath: "/surveys/$surveyId"
      preLoaderRoute: typeof BaseSurveysSurveyIdRouteImport
      parentRoute: typeof BaseImport
    }
    "/_base/blog/": {
      id: "/_base/blog/"
      path: "/"
      fullPath: "/blog/"
      preLoaderRoute: typeof BaseBlogIndexImport
      parentRoute: typeof BaseBlogRouteImport
    }
    "/_base/surveys/": {
      id: "/_base/surveys/"
      path: "/"
      fullPath: "/surveys/"
      preLoaderRoute: typeof BaseSurveysIndexImport
      parentRoute: typeof BaseSurveysRouteImport
    }
    "/_base/blog/$postId/": {
      id: "/_base/blog/$postId/"
      path: "/"
      fullPath: "/blog/$postId/"
      preLoaderRoute: typeof BaseBlogPostIdIndexImport
      parentRoute: typeof BaseBlogPostIdRouteImport
    }
    "/_base/surveys/$surveyId/": {
      id: "/_base/surveys/$surveyId/"
      path: "/"
      fullPath: "/surveys/$surveyId/"
      preLoaderRoute: typeof BaseSurveysSurveyIdIndexImport
      parentRoute: typeof BaseSurveysSurveyIdRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  BaseRoute: BaseRoute.addChildren({
    BaseBlogRouteRoute: BaseBlogRouteRoute.addChildren({
      BaseBlogPostIdRouteRoute: BaseBlogPostIdRouteRoute.addChildren({
        BaseBlogPostIdIndexRoute,
      }),
      BaseBlogIndexRoute,
    }),
    BaseSurveysRouteRoute: BaseSurveysRouteRoute.addChildren({
      BaseSurveysIndexRoute,
    }),
    BaseIndexRoute,
    BaseSurveysSurveyIdRouteRoute: BaseSurveysSurveyIdRouteRoute.addChildren({
      BaseSurveysSurveyIdIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_base"
      ]
    },
    "/_base": {
      "filePath": "_base.tsx",
      "children": [
        "/_base/blog",
        "/_base/surveys",
        "/_base/",
        "/_base/surveys/$surveyId"
      ]
    },
    "/_base/blog": {
      "filePath": "_base/blog/route.tsx",
      "parent": "/_base",
      "children": [
        "/_base/blog/$postId",
        "/_base/blog/"
      ]
    },
    "/_base/surveys": {
      "filePath": "_base/surveys/route.tsx",
      "parent": "/_base",
      "children": [
        "/_base/surveys/"
      ]
    },
    "/_base/": {
      "filePath": "_base/index.tsx",
      "parent": "/_base"
    },
    "/_base/blog/$postId": {
      "filePath": "_base/blog/$postId/route.tsx",
      "parent": "/_base/blog",
      "children": [
        "/_base/blog/$postId/"
      ]
    },
    "/_base/surveys/$surveyId": {
      "filePath": "_base/surveys_/$surveyId/route.tsx",
      "parent": "/_base",
      "children": [
        "/_base/surveys/$surveyId/"
      ]
    },
    "/_base/blog/": {
      "filePath": "_base/blog/index.tsx",
      "parent": "/_base/blog"
    },
    "/_base/surveys/": {
      "filePath": "_base/surveys/index.tsx",
      "parent": "/_base/surveys"
    },
    "/_base/blog/$postId/": {
      "filePath": "_base/blog/$postId/index.tsx",
      "parent": "/_base/blog/$postId"
    },
    "/_base/surveys/$surveyId/": {
      "filePath": "_base/surveys_/$surveyId/index.tsx",
      "parent": "/_base/surveys/$surveyId"
    }
  }
}
ROUTE_MANIFEST_END */
